import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import GridOfUsers from '@/views/GridOfUsers'
import Container from '@mui/material/Container'
import Card from '@/components/Card'
import { UsersContext } from '@/context/UsersContext'


export default function Home({ data }) {

  console.log('data', data);
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
      <UsersContext.Provider value={data}>
        <GridOfUsers />
      </UsersContext.Provider>

        {/* <Container maxWidth="sm">
          <Card />
        </Container> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
  const data = await res.json()

  return { props: { data } }
}
