import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import GridOfUsers from '@/routes/GridOfUsers'


export default function Home() {

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
          <GridOfUsers />
      </main>
    </div>
  )
}

// export async function getServerSideProps(context) {
//   const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
//   const data = await res.json()

//   return { props: { data } }
// }
